    token:                     "MTE4MjAxNzEwMTg5NzE1NDYyMQ.GlI-_9.HLWsEfvWFwtn0xb9bqmgpuN2k4lPJxORvLw1Ic"
    devtoken:                  "MTIyNjgxNzg3NDUwOTk1NTE4Mw.GBCjM8.XUiQSdfvlgXdsUs2DqiFbxFzr2cP8KN5pkk8Hw"
    link:                      "https://discord.com/api/oauth2/authorize?client_id=1182017101897154621&permissions=277025778752&scope=bot+applications.commands"
    devlink:                   "https://discord.com/oauth2/authorize?client_id=1226817874509955183&permissions=277025778752&scope=bot+applications.commands"
    devmode:                   true
    windows:                   false
    developers:
        - 455678466793144320   # ainawastaken
        - 686120923039793179   # _kalibr
        - 1142560634421133413  # kalibr_2
        - 1059851063584358491  # malorussia
        - 643945264868098049   # ?
        - 1149761243800928458  # martoonka
        - 1004332890542329886  # martoonishka
        - 1189973639123185675  # kalibr3rd
        - 658384793708527626   # fanfurik_
    commands:
        "reload":              "Reload tanks (requires developer)"
        "getcfg":              "Gets config of current guild (requires developer)"
        "trigger":             "Triggers a spawn (requires developer)"
        "activate":            "Activate the bot"
        "disable":             "Disable the bot"
        "completion":          "Shows your tank completion"
        "setcdn":              "Sets CDN channel of bot"
        "info":                "Gets the info of all your tanks"
        "give":                "Gives tank to target user"