token:                     "MTIzNTQzNjg2Mjg2MTA4NjcyMA.G1c147.aI8nj4dnutiJj6vxetkN5qjcQPaoARX8X9HdXY"
devtoken:                  "MTI2MTk5MTk4NjY4MTA5MDEwMA.G_lynm.9_DJFgv_1JTJqJ5MIvfgXFM5LTPlKpdKYs_FCg"
link:                      "https://discord.com/oauth2/authorize?client_id=1235436862861086720&permissions=277025778752&scope=bot+applications.commands"
devlink:                   "https://discord.com/oauth2/authorize?client_id=1261991986681090100&permissions=277025778752&scope=bot+applications.commands"
devmode:                   true
windows:                   false
master: 658384793708527626 # ainamk2
developers:
    - 455678466793144320   # ainawastaken
    - 686120923039793179   # _kalibr
    - 1142560634421133413  # kalibr_2
    - 1059851063584358491  # malorussia
    - 643945264868098049   # ?
    - 1149761243800928458  # martoonka
    - 1004332890542329886  # martoonishka
    - 1189973639123185675  # kalibr3rd
    - 810900598525919252   # kalizigger
    - 658384793708527626   # ainamk2
    - 718203079429849158   # rgfsoldat
commands:
#    "reload":              "Reload tanks (requires developer)"
#    "getcfg":              "Gets config of current guild (requires developer)"
#    "trigger":             "Triggers a spawn (requires developer)"
    "activate":            "Activate the bot (requires role with administrator)"
    "disable":             "Disable the bot (requires role with administrator)"
    "completion":          "Shows your tank completion"
#    "setcdn":              "Sets CDN channel of bot"
    "info":                "Gets the info of all your tanks"
    "give":                "Gives tank to target user"
    "invite":              "Gets the bot invite link"
    "help":                "Displays the list of command"
    "leaderboard":         "Leaderboard of this server"
    "globalleaderboard":   "Global leaderboard"
    "serverleaderboard":   "Global server leaderboard"
VERSION:                   2.1